{{NAME_ROUTE_SANITIZED}}-plugin:
  needs: [publish]
  runs-on: ubuntu-latest
  if: contains(needs.publish.outputs.changed, '{{NAME_ROUTE}}')
  env:
    TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  steps:
    - name: "Checkout"
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Publish Plugin - {{LOCATION}}
      run: |
        cd {{LOCATION}}
        yarn plugin:publish
      env:
        TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
        TURBO_TEAM: ${{ vars.TURBO_TEAM }} 