  publish-plugins:
    needs: webhook
    runs-on: ubuntu-latest
    if: always() && !failure() && !cancelled()
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    steps:
      - name: "Checkout ${{ github.ref_name }}"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Resync from  ${{ github.ref_name }}"
        run: |
          git pull origin ${{ github.ref_name }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: "Install minimal dependencies (build is already done)"
        run: |
          yarn workspaces focus  @runeya/common-plugin-packager @runeya/runeya $(find plugins/* -maxdepth 0 -type d | sed 's|plugins/|@runeya/plugins-|' | tr '\n' ' ')

      - name: "Build and publish plugins packages to runeya"
        if: contains(github.ref_name, 'master')
        env:
          PLUGINS_API_URL: ${{ secrets.PLUGINS_API_URL }}
          PLUGINS_API_KEY: ${{ secrets.PLUGINS_API_KEY }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "Attempting to build and publish plugins package to runeya..."
          npx turbo run plugin:publish $(find plugins/* -maxdepth 0 -type d | sed 's|plugins/|--filter=@runeya/plugins-|' | tr '\n' ' ') --env-mode=loose

      