export default [
  { code: 'af', fr: 'Afghanistan', en: 'Afghanistan' },
  { code: 'za', fr: 'Afrique du Sud', en: 'South Africa' },
  { code: 'al', fr: 'Albanie', en: 'Albania' },
  { code: 'dz', fr: 'Algérie', en: 'Algeria' },
  { code: 'de', fr: 'Allemagne', en: 'Germany' },
  { code: 'ad', fr: 'Andorre', en: 'Andorra' },
  { code: 'ao', fr: 'Angola', en: 'Angola' },
  { code: 'ai', fr: 'Anguilla', en: 'Anguilla' },
  { code: 'aq', fr: 'Antarctique', en: 'Antarctica' },
  { code: 'ag', fr: 'Antigua-et-Barbuda', en: 'Antigua and Barbuda' },
  { code: 'sa', fr: 'Arabie Saoudite', en: 'Saudi Arabia' },
  { code: 'ar', fr: 'Argentine', en: 'Argentina' },
  { code: 'am', fr: 'Arménie', en: 'Armenia' },
  { code: 'aw', fr: 'Aruba', en: 'Aruba' },
  { code: 'au', fr: 'Australie', en: 'Australia' },
  { code: 'at', fr: 'Autriche', en: 'Austria' },
  { code: 'az', fr: 'Azerbaïdjan', en: 'Azerbaijan' },
  { code: 'bs', fr: 'Bahamas', en: 'Bahamas' },
  { code: 'bh', fr: 'Bahreïn', en: 'Bahrain' },
  { code: 'bd', fr: 'Bangladesh', en: 'Bangladesh' },
  { code: 'bb', fr: 'Barbade', en: 'Barbados' },
  { code: 'be', fr: 'Belgique', en: 'Belgium' },
  { code: 'bz', fr: 'Belize', en: 'Belize' },
  { code: 'bj', fr: 'Bénin', en: 'Benin' },
  { code: 'bm', fr: 'Bermudes', en: 'Bermuda' },
  { code: 'bt', fr: 'Bhoutan', en: 'Bhutan' },
  { code: 'by', fr: 'Biélorussie', en: 'Belarus' },
  { code: 'bo', fr: 'Bolivie', en: 'Bolivia' },
  { code: 'ba', fr: 'Bosnie-Herzégovine', en: 'Bosnia and Herzegovina' },
  { code: 'bw', fr: 'Botswana', en: 'Botswana' },
  { code: 'br', fr: 'Brésil', en: 'Brazil' },
  { code: 'bn', fr: 'Brunei', en: 'Brunei Darussalam' },
  { code: 'bg', fr: 'Bulgarie', en: 'Bulgaria' },
  { code: 'bf', fr: 'Burkina Faso', en: 'Burkina Faso' },
  { code: 'bi', fr: 'Burundi', en: 'Burundi' },
  { code: 'kh', fr: 'Cambodge', en: 'Cambodia' },
  { code: 'cm', fr: 'Cameroun', en: 'Cameroon' },
  { code: 'ca', fr: 'Canada', en: 'Canada' },
  { code: 'cv', fr: 'Cap-Vert', en: 'Cape Verde' },
  { code: 'cl', fr: 'Chili', en: 'Chile' },
  { code: 'cn', fr: 'Chine', en: 'China' },
  { code: 'cy', fr: 'Chypre', en: 'Cyprus' },
  { code: 'co', fr: 'Colombie', en: 'Colombia' },
  { code: 'km', fr: 'Comores', en: 'Comoros' },
  { code: 'cg', fr: 'Congo', en: 'Congo' },
  { code: 'cd', fr: 'Congo, République démocratique du', en: 'Congo, Democratic Republic of' },
  { code: 'kp', fr: 'Corée du Nord', en: 'North Korea' },
  { code: 'kr', fr: 'Corée du Sud', en: 'South Korea' },
  { code: 'cr', fr: 'Costa Rica', en: 'Costa Rica' },
  { code: 'ci', fr: 'Côte d\'Ivoire', en: 'Ivory Coast' },
  { code: 'hr', fr: 'Croatie', en: 'Croatia' },
  { code: 'cu', fr: 'Cuba', en: 'Cuba' },
  { code: 'dk', fr: 'Danemark', en: 'Denmark' },
  { code: 'dj', fr: 'Djibouti', en: 'Djibouti' },
  { code: 'dm', fr: 'Dominique', en: 'Dominica' },
  { code: 'eg', fr: 'Égypte', en: 'Egypt' },
  { code: 'ae', fr: 'Émirats arabes unis', en: 'United Arab Emirates' },
  { code: 'ec', fr: 'Équateur', en: 'Ecuador' },
  { code: 'er', fr: 'Érythrée', en: 'Eritrea' },
  { code: 'es', fr: 'Espagne', en: 'Spain' },
  { code: 'ee', fr: 'Estonie', en: 'Estonia' },
  { code: 'us', fr: 'États-Unis', en: 'United States' },
  { code: 'et', fr: 'Éthiopie', en: 'Ethiopia' },
  { code: 'fr', fr: 'France', en: 'France' },
  { code: 'ga', fr: 'Gabon', en: 'Gabon' },
  { code: 'gm', fr: 'Gambie', en: 'Gambia' },
  { code: 'ge', fr: 'Géorgie', en: 'Georgia' },
  { code: 'gh', fr: 'Ghana', en: 'Ghana' },
  { code: 'gi', fr: 'Gibraltar', en: 'Gibraltar' },
  { code: 'gr', fr: 'Grèce', en: 'Greece' },
  { code: 'gd', fr: 'Grenade', en: 'Grenada' },
  { code: 'gl', fr: 'Groenland', en: 'Greenland' },
  { code: 'gp', fr: 'Guadeloupe', en: 'Guadeloupe' },
  { code: 'gu', fr: 'Guam', en: 'Guam' },
  { code: 'gt', fr: 'Guatemala', en: 'Guatemala' },
  { code: 'gn', fr: 'Guinée', en: 'Guinea' },
  { code: 'gq', fr: 'Guinée équatoriale', en: 'Equatorial Guinea' },
  { code: 'gw', fr: 'Guinée-Bissau', en: 'Guinea-Bissau' },
  { code: 'gy', fr: 'Guyana', en: 'Guyana' },
  { code: 'ht', fr: 'Haïti', en: 'Haiti' },
  { code: 'hn', fr: 'Honduras', en: 'Honduras' },
  { code: 'hk', fr: 'Hong Kong', en: 'Hong Kong' },
  { code: 'hu', fr: 'Hongrie', en: 'Hungary' },
  { code: 'in', fr: 'Inde', en: 'India' },
  { code: 'id', fr: 'Indonésie', en: 'Indonesia' },
  { code: 'ir', fr: 'Iran', en: 'Iran' },
  { code: 'iq', fr: 'Iraq', en: 'Iraq' },
  { code: 'ie', fr: 'Irlande', en: 'Ireland' },
  { code: 'is', fr: 'Islande', en: 'Iceland' },
  { code: 'il', fr: 'Israël', en: 'Israel' },
  { code: 'it', fr: 'Italie', en: 'Italy' },
  { code: 'jm', fr: 'Jamaïque', en: 'Jamaica' },
  { code: 'jp', fr: 'Japon', en: 'Japan' },
  { code: 'jo', fr: 'Jordanie', en: 'Jordan' },
  { code: 'kz', fr: 'Kazakhstan', en: 'Kazakhstan' },
  { code: 'ke', fr: 'Kenya', en: 'Kenya' },
  { code: 'kg', fr: 'Kirghizistan', en: 'Kyrgyzstan' },
  { code: 'ki', fr: 'Kiribati', en: 'Kiribati' },
  { code: 'kw', fr: 'Koweït', en: 'Kuwait' },
  { code: 'la', fr: 'Laos', en: 'Laos' },
  { code: 'ls', fr: 'Lesotho', en: 'Lesotho' },
  { code: 'lv', fr: 'Lettonie', en: 'Latvia' },
  { code: 'lb', fr: 'Liban', en: 'Lebanon' },
  { code: 'lr', fr: 'Libéria', en: 'Liberia' },
  { code: 'ly', fr: 'Libye', en: 'Libya' },
  { code: 'li', fr: 'Liechtenstein', en: 'Liechtenstein' },
  { code: 'lt', fr: 'Lituanie', en: 'Lithuania' },
  { code: 'lu', fr: 'Luxembourg', en: 'Luxembourg' },
  { code: 'mg', fr: 'Madagascar', en: 'Madagascar' },
  { code: 'my', fr: 'Malaisie', en: 'Malaysia' },
  { code: 'mw', fr: 'Malawi', en: 'Malawi' },
  { code: 'mv', fr: 'Maldives', en: 'Maldives' },
  { code: 'ml', fr: 'Mali', en: 'Mali' },
  { code: 'mt', fr: 'Malte', en: 'Malta' },
  { code: 'ma', fr: 'Maroc', en: 'Morocco' },
  { code: 'mu', fr: 'Maurice', en: 'Mauritius' },
  { code: 'mr', fr: 'Mauritanie', en: 'Mauritania' },
  { code: 'mx', fr: 'Mexique', en: 'Mexico' },
  { code: 'mc', fr: 'Monaco', en: 'Monaco' },
  { code: 'mn', fr: 'Mongolie', en: 'Mongolia' },
  { code: 'me', fr: 'Monténégro', en: 'Montenegro' },
  { code: 'ms', fr: 'Montserrat', en: 'Montserrat' },
  { code: 'mz', fr: 'Mozambique', en: 'Mozambique' },
  { code: 'na', fr: 'Namibie', en: 'Namibia' },
  { code: 'nr', fr: 'Nauru', en: 'Nauru' },
  { code: 'np', fr: 'Népal', en: 'Nepal' },
  { code: 'ni', fr: 'Nicaragua', en: 'Nicaragua' },
  { code: 'ne', fr: 'Niger', en: 'Niger' },
  { code: 'ng', fr: 'Nigeria', en: 'Nigeria' },
  { code: 'nu', fr: 'Niue', en: 'Niue' },
  { code: 'no', fr: 'Norvège', en: 'Norway' },
  { code: 'nz', fr: 'Nouvelle-Zélande', en: 'New Zealand' },
  { code: 'om', fr: 'Oman', en: 'Oman' },
  { code: 'ug', fr: 'Ouganda', en: 'Uganda' },
  { code: 'uz', fr: 'Ouzbékistan', en: 'Uzbekistan' },
  { code: 'pk', fr: 'Pakistan', en: 'Pakistan' },
  { code: 'pw', fr: 'Palaos', en: 'Palau' },
  { code: 'ps', fr: 'Palestine', en: 'Palestine' },
  { code: 'pa', fr: 'Panama', en: 'Panama' },
  { code: 'pg', fr: 'Papouasie-Nouvelle-Guinée', en: 'Papua New Guinea' },
  { code: 'py', fr: 'Paraguay', en: 'Paraguay' },
  { code: 'nl', fr: 'Pays-Bas', en: 'Netherlands' },
  { code: 'pe', fr: 'Pérou', en: 'Peru' },
  { code: 'ph', fr: 'Philippines', en: 'Philippines' },
  { code: 'pl', fr: 'Pologne', en: 'Poland' },
  { code: 'pt', fr: 'Portugal', en: 'Portugal' },
  { code: 'qa', fr: 'Qatar', en: 'Qatar' },
  { code: 'ro', fr: 'Roumanie', en: 'Romania' },
  { code: 'gb', fr: 'Royaume-Uni', en: 'United Kingdom' },
  { code: 'ru', fr: 'Russie', en: 'Russia' },
  { code: 'rw', fr: 'Rwanda', en: 'Rwanda' },
  { code: 'sn', fr: 'Sénégal', en: 'Senegal' },
  { code: 'rs', fr: 'Serbie', en: 'Serbia' },
  { code: 'sc', fr: 'Seychelles', en: 'Seychelles' },
  { code: 'sl', fr: 'Sierra Leone', en: 'Sierra Leone' },
  { code: 'sg', fr: 'Singapour', en: 'Singapore' },
  { code: 'sk', fr: 'Slovaquie', en: 'Slovakia' },
  { code: 'si', fr: 'Slovénie', en: 'Slovenia' },
  { code: 'so', fr: 'Somalie', en: 'Somalia' },
  { code: 'sd', fr: 'Soudan', en: 'Sudan' },
  { code: 'lk', fr: 'Sri Lanka', en: 'Sri Lanka' },
  { code: 'se', fr: 'Suède', en: 'Sweden' },
  { code: 'ch', fr: 'Suisse', en: 'Switzerland' },
  { code: 'sr', fr: 'Suriname', en: 'Suriname' },
  { code: 'sz', fr: 'Swaziland', en: 'Swaziland' },
  { code: 'sy', fr: 'Syrie', en: 'Syria' },
  { code: 'tj', fr: 'Tadjikistan', en: 'Tajikistan' },
  { code: 'tw', fr: 'Taïwan', en: 'Taiwan' },
  { code: 'tz', fr: 'Tanzanie', en: 'Tanzania' },
  { code: 'td', fr: 'Tchad', en: 'Chad' },
  { code: 'th', fr: 'Thaïlande', en: 'Thailand' },
  { code: 'tg', fr: 'Togo', en: 'Togo' },
  { code: 'to', fr: 'Tonga', en: 'Tonga' },
  { code: 'tt', fr: 'Trinité-et-Tobago', en: 'Trinidad and Tobago' },
  { code: 'tn', fr: 'Tunisie', en: 'Tunisia' },
  { code: 'tm', fr: 'Turkménistan', en: 'Turkmenistan' },
  { code: 'tr', fr: 'Turquie', en: 'Turkey' },
  { code: 'tv', fr: 'Tuvalu', en: 'Tuvalu' },
  { code: 'ua', fr: 'Ukraine', en: 'Ukraine' },
  { code: 'uy', fr: 'Uruguay', en: 'Uruguay' },
  { code: 'vu', fr: 'Vanuatu', en: 'Vanuatu' },
  { code: 'va', fr: 'Vatican', en: 'Vatican' },
  { code: 've', fr: 'Venezuela', en: 'Venezuela' },
  { code: 'vn', fr: 'Vietnam', en: 'Vietnam' },
  { code: 'ye', fr: 'Yémen', en: 'Yemen' },
  { code: 'zm', fr: 'Zambie', en: 'Zambia' },
  { code: 'zw', fr: 'Zimbabwe', en: 'Zimbabwe' }
];
